/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as LogRouteImport } from './routes/log'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MealMealRouteImport } from './routes/meal.$meal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MealMealRoute = MealMealRouteImport.update({
  id: '/meal/$meal',
  path: '/meal/$meal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/log': typeof LogRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/meal/$meal': typeof MealMealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/log': typeof LogRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/meal/$meal': typeof MealMealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/log': typeof LogRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/meal/$meal': typeof MealMealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/advisor' | '/log' | '/progress' | '/settings' | '/meal/$meal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advisor' | '/log' | '/progress' | '/settings' | '/meal/$meal'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/log'
    | '/progress'
    | '/settings'
    | '/meal/$meal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  LogRoute: typeof LogRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  MealMealRoute: typeof MealMealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$meal': {
      id: '/meal/$meal'
      path: '/meal/$meal'
      fullPath: '/meal/$meal'
      preLoaderRoute: typeof MealMealRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  LogRoute: LogRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  MealMealRoute: MealMealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
